=== olsn-bit/miprojects/dtd_correu.dtd
<!ELEMENT enviados (correu)>
  <!ELEMENT correu (emissor, objecte, enviament, receptor)>
    <!ELEMENT emissor (nom_emissor, telefon_emissor, email_emissor?,adresa_emissor)>
      <!ELEMENT nom_emissor (#PCDATA)>
      <!ELEMENT telefon_emissor (#PCDATA)>
      <!ELEMENT email_emissor (#PCDATA)>
      <!ELEMENT adresa_emissor (#PCDATA)>
      <!ATTLIST emissor sexe_emissor CDATA #REQUIRED>
      <!ATTLIST telefon_emissor pais_emissor CDATA #REQUIRED>
    <!ELEMENT objecte (tipus, pes, descripcio?, fragil, refrigeracio)>
      <!ELEMENT tipus (#PCDATA)>
      <!ELEMENT pes (#PCDATA)>
      <!ELEMENT descripcio (#PCDATA)>
      <!ELEMENT fragil (#PCDATA)>
      <!ELEMENT refrigeracio (#PCDATA)>
      <!ATTLIST objecte codi_enviament ID #REQUIRED>
    <!ELEMENT enviament (data, retornable, entregat, prioritat, transport)>
      <!ELEMENT data (#PCDATA)>
      <!ELEMENT retornable (#PCDATA)>
      <!ELEMENT entregat (#PCDATA)>
      <!ELEMENT prioritat (#PCDATA)>
      <!ELEMENT transport (#PCDATA)>
    <!ELEMENT receptor (nom_receptor, telefon_receptor, email_receptor?,adresa_receptor)>
      <!ELEMENT nom_receptor (#PCDATA)>
      <!ELEMENT telefon_receptor (#PCDATA)>
      <!ELEMENT email_receptor (#PCDATA)>
      <!ELEMENT adresa_receptor (#PCDATA)>
      <!ATTLIST receptor sexe_receptor CDATA #REQUIRED>
      <!ATTLIST telefon_receptor pais_receptor CDATA #REQUIRED>

=== olsn-bit/miprojects/correufinal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE enviados SYSTEM "dtd_correu.dtd">
<enviados>
  <correu>
    <emissor sexe_emissor="Home">
      <nom_emissor>David Falco</nom_emissor>
      <telefon_emissor pais_emissor="España">675676567</telefon_emissor>
      <email_emissor>davidfalco@iesmontsia.org</email_emissor>
      <adresa_emissor>Espanya,Tarragona,Sant Carles de la Ràpita,c/santapinga 23 planta 3 porta 2</adresa_emissor>
    </emissor>
    <objecte codi_enviament="id_1">
      <tipus>paquet</tipus>
      <pes>200g</pes>
      <descripcio></descripcio>
      <fragil>no</fragil>
      <refrigeracio>no</refrigeracio>
    </objecte>
    <enviament>
      <data>22/22/22</data>
      <retornable>si</retornable>
      <entregat>no</entregat>
      <prioritat>alta</prioritat>
      <transport>camio</transport>
    </enviament>
    <receptor sexe_receptor="Dona">
      <nom_receptor>Alberta Das Santas</nom_receptor>
      <telefon_receptor pais_receptor="España">763639373</telefon_receptor>
      <email_receptor>albertadassantas@iesmontsia.org</email_receptor>
      <adresa_receptor>Espanya,Tarragona,Sant Carles de la Ràpita,c/santapinga 23 planta 3 porta 3</adresa_receptor>
    </receptor>
  </correu>
</enviados>
